token: ' '

dataset: 'https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv'

plot_config:
  title: Iris flower analysis
  xlabel: Sepal Lenth
  ylabel : Sepal Width


columns:
- lenth
- width

plot_color: green


